### ISSUE TITLE
keras-retinanet package is not Available

### ISSUE THREAD

**Issue by praveench2398** [vaghawan/airbus-ship-detection-using-keras-retinanet-maskrcnn#1]
In this code you have used  keras_retinanet packages in train.py but there are no such packages in repo.Do we need to add packages separately.

**Comment by vaghawan** [comment]
Yes, that's a seperate pacckage. You're to get keras_retinanet from here: https://github.com/fizyr/keras-retinanet

**Comment by praveench2398** [comment]
> Yes, that's a seperate pacckage. You're to get keras_retinanet from here: https://github.com/fizyr/keras-retinanet

Using TensorFlow backend.
2020-04-21 06:07:41.096807: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/content/drive/My Drive/keras-maskrcnn-master/keras-maskrcnn-master/keras_maskrcnn/bin/train.py", line 27, in <module>
    from keras_retinanet.utils.config import read_config_file, parse_anchor_parameters
  File "/usr/local/lib/python3.6/dist-packages/keras_maskrcnn-0.2.2-py3.6.egg/keras_retinanet/utils/config.py", line 20, in <module>
    from ..utils.anchors import AnchorParameters
  File "/usr/local/lib/python3.6/dist-packages/keras_maskrcnn-0.2.2-py3.6.egg/keras_retinanet/utils/anchors.py", line 20, in <module>
    from ..utils.compute_overlap import compute_overlap
ModuleNotFoundError: No module named 'keras_retinanet.utils.compute_overlap'

Even after taking that package iam getting the following error.I know that this error occurs because of not running python setup.py built-ext --inplace.
But Your repo has setup.py and keras retinanet has separate setup.py which one to run.

**Comment by praveench2398** [comment]
> Yes, that's a seperate pacckage. You're to get keras_retinanet from here: https://github.com/fizyr/keras-retinanet

My goal is to bring the output of retinanet with mask.can you suggest me any other techniques to do that

**Comment by vaghawan** [comment]
> > Yes, that's a seperate pacckage. You're to get keras_retinanet from here: https://github.com/fizyr/keras-retinanet
> 
> Using TensorFlow backend.
> 2020-04-21 06:07:41.096807: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
> Traceback (most recent call last):
> File "/content/drive/My Drive/keras-maskrcnn-master/keras-maskrcnn-master/keras_maskrcnn/bin/train.py", line 27, in
> from keras_retinanet.utils.config import read_config_file, parse_anchor_parameters
> File "/usr/local/lib/python3.6/dist-packages/keras_maskrcnn-0.2.2-py3.6.egg/keras_retinanet/utils/config.py", line 20, in
> from ..utils.anchors import AnchorParameters
> File "/usr/local/lib/python3.6/dist-packages/keras_maskrcnn-0.2.2-py3.6.egg/keras_retinanet/utils/anchors.py", line 20, in
> from ..utils.compute_overlap import compute_overlap
> ModuleNotFoundError: No module named 'keras_retinanet.utils.compute_overlap'
> 
> Even after taking that package iam getting the following error.I know that this error occurs because of not running python setup.py built-ext --inplace.
> But Your repo has setup.py and keras retinanet has separate setup.py which one to run.

Well, run both. You need separate installation of keras-retinanet.
