### ISSUE TITLE
How to convert to tf-serving ?

### ISSUE THREAD

**Issue by ajinkya933** [vaghawan/airbus-ship-detection-using-keras-retinanet-maskrcnn#3]
How do I convert your model to tensorflow serving format?

**Comment by vaghawan** [comment]
I've not done it myself, but you could easily find something on the internet. Check this: 

https://github.com/bendangnuksung/mrcnn_serving_ready 

One quick google search gave me this. 

![Screenshot from 2020-05-11 16-25-07](https://user-images.githubusercontent.com/13087930/81552938-12f22480-93a4-11ea-86d5-57cd097deba6.png)
